#!/usr/bin/env bash
# One-shot local setup for Linux hosts. Mirrors what .devcontainer/Dockerfile
# does, so the container and a bare host converge on the same environment.
#
# Usage:  ./scripts/local_setup.sh
#
# Re-run safely: apt install is idempotent, ONNX Runtime install skips if
# already present, and the model fetch is a no-op if the file exists.

set -euo pipefail

ORT_VER="${ORT_VER:-1.20.1}"
ORT_PREFIX="/opt/onnxruntime"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

echo "==> Installing apt packages from .devcontainer/apt-packages.txt"
sudo apt-get update
grep -vE '^\s*(#|$)' .devcontainer/apt-packages.txt \
    | sudo xargs apt-get install -y --no-install-recommends

if [[ -f "${ORT_PREFIX}/lib/libonnxruntime.so" ]]; then
    echo "==> ONNX Runtime already installed at ${ORT_PREFIX} — skipping"
else
    echo "==> Installing ONNX Runtime ${ORT_VER} to ${ORT_PREFIX}"
    curl -fsSL -o /tmp/ort.tgz \
        "https://github.com/microsoft/onnxruntime/releases/download/v${ORT_VER}/onnxruntime-linux-x64-${ORT_VER}.tgz"
    sudo mkdir -p "${ORT_PREFIX}"
    sudo tar -xzf /tmp/ort.tgz --strip-components=1 -C "${ORT_PREFIX}"
    rm /tmp/ort.tgz
fi

# Write an env file the user can `source` in future shells so cmake and the
# built binary can find ONNX Runtime. Exports don't survive past this script.
ENV_FILE="${REPO_ROOT}/scripts/local_env.sh"
cat > "${ENV_FILE}" <<EOF
# Generated by scripts/local_setup.sh — source this before building or running:
#   source scripts/local_env.sh
export CMAKE_PREFIX_PATH="${ORT_PREFIX}\${CMAKE_PREFIX_PATH:+:\${CMAKE_PREFIX_PATH}}"
export LD_LIBRARY_PATH="${ORT_PREFIX}/lib\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}"
EOF
echo "==> Wrote ${ENV_FILE}"

echo "==> Fetching YOLOv10m model"
bash .devcontainer/post-create.sh

# shellcheck disable=SC1090
source "${ENV_FILE}"

echo "==> Configuring and building (preset: dev)"
cmake --preset dev
cmake --build --preset dev

echo
echo "Done. In new shells, run:  source scripts/local_env.sh  before ./build-ninja/obj_tracker_cpp"
